project_id = "mroxxnzbsrmacjlrfvhr"

[functions.send-form-notification]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.article-html]
verify_jwt = false

[functions.insights-index]
verify_jwt = false

[functions.manual-fulfill]
verify_jwt = false
