project_id = "mroxxnzbsrmacjlrfvhr"

[functions.send-form-notification]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-test-emails]
verify_jwt = false

[functions.sitemap]
verify_jwt = false
